<a href="https://colab.research.google.com/github/ChekkaHarshaVardhan/AI_ML_Avanthi_Harsha/blob/main/Day4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [11]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [6]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
# Get Dimension
a.ndim

1

In [12]:
# Get shape
b.shape

(2, 3)

In [13]:
# Get number of elements
a.size

3

In [14]:
# Get Type
a.dtype

dtype('int64')

In [15]:
# Gat size
a = np.array([1,2,3], dtype='int16')
a.itemsize

2

In [16]:
# print the abive matrix using numpy
a = np.ones((5,5))

inside = np.zeros((3,3))
inside[1,1] = 9
a[1:4,-4:-1] = inside
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
