<a href="https://colab.research.google.com/github/ChekkaHarshaVardhan/AI_ML_Avanthi_Harsha/blob/main/NUMPY_PY.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install numpy

In [3]:
import numpy as np

In [4]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [5]:
a = np.array([1,2,3])
print(a)


[1 2 3]


In [6]:
# Get Dimension
a.ndim

1

In [8]:
# Get shape
b.shape

(2, 3)

In [9]:
# Get number of elements
a.size

3

In [11]:
# Get Type
a.dtype

dtype('int64')

In [12]:
# Gat size
a = np.array([1,2,3], dtype='int16')
a.itemsize

2

In [13]:
# print the abive matrix using numpy
a = np.ones((5,5))

inside = np.zeros((3,3))
inside[1,1] = 9
a[1:4,-4:-1] = inside
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
a = np.zeros((10))
a[4]=1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [15]:
a=np.random.randint(10,49,size=(10))
print(a)

[33 35 22 10 26 36 21 31 21 15]


In [16]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [17]:
a=np.arange(1,11)
print(a)
a[::-1]

[ 1  2  3  4  5  6  7  8  9 10]


array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [18]:
x=np.arange(0,9)
b=x.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:

a=np.random.randint(0,8,size=(3,3))
print(a)
a[3:3]


[[4 4 5]
 [1 6 0]
 [6 3 1]]


array([], shape=(0, 3), dtype=int64)

In [28]:
a = np.random.randint(1,100, size = (10,10))


In [24]:
a = np.random.randint(1,100, size = (10,10))
print("Max = ", np.max(a))
print("Min = ", np.min(a))


Max =  96
Min =  2


In [26]:
x=np.ones((4,4))
x[1:-1,1:-1]=0
print(x)

[[1. 1. 1. 1.]
 [1. 0. 0. 1.]
 [1. 0. 0. 1.]
 [1. 1. 1. 1.]]


In [27]:
x=np.zeros((8,8))
x[1::2,::2]=1
x[::2,1::2]=1
x

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [29]:
x=np.random.rand(5,3)
print(x)
y=np.random.rand(3,2)
print(y)
np.matmul(x,y)

[[0.3608324  0.78951878 0.50422725]
 [0.2235048  0.37321238 0.54443281]
 [0.56944744 0.30026926 0.77680884]
 [0.54032869 0.96946762 0.15801717]
 [0.33049359 0.09468649 0.69055361]]
[[0.88550374 0.58436826]
 [0.85891307 0.141064  ]
 [0.20208968 0.5441665 ]]


array([[1.09954557, 0.59661526],
       [0.62849558, 0.47951804],
       [0.91913808, 0.79783754],
       [1.34308513, 0.53849557],
       [0.51353453, 0.58226296]])

In [30]:
x = np.array([0, 1, 2, 3, 4])
y=np.array([1, 3, 4])
print(np.intersect1d(x,y))

[1 3 4]


In [31]:
x=np.random.rand(10)
print(x)
x.sort()
print(x)


[0.51792349 0.97154752 0.618652   0.26987566 0.15943665 0.61832164
 0.37868744 0.1133537  0.2410567  0.09306559]
[0.09306559 0.1133537  0.15943665 0.2410567  0.26987566 0.37868744
 0.51792349 0.61832164 0.618652   0.97154752]
